definitions:
  http.LoginReq:
    properties:
      passwd:
        type: string
      uid:
        type: integer
    type: object
  http.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: localhost:11080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Nethopper Micro Server - Gate
  version: 1.0.2
paths:
  /call/LoginHandler:
    put:
      consumes:
      - text/plain
      parameters:
      - description: UserID
        in: query
        name: uid
        required: true
        type: string
      - description: Password
        in: query
        name: pwd
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: LoginHandler
      tags:
      - LogicModule
  /v1/:
    post:
      consumes:
      - application/json
      parameters:
      - description: LoginReq
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/http.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
      summary: 登录
      tags:
      - http web 模块
  /v1/call/:module/:cmd/:opt:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: module
        in: query
        name: module
        required: true
        type: integer
      - description: cmd
        in: query
        name: cmd
        required: true
        type: string
      - description: opt
        in: query
        name: opt
        required: true
        type: integer
      - description: data
        in: formData
        name: data
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
      summary: 登录
      tags:
      - http web 模块
swagger: "2.0"
